# Used only for DEVELOPMENT
 
version: '3.7'
 
services:
  postgres:
    image: postgres:12.2-alpine
    environment:
      POSTGRES_USER: '${POSTGRESQL_ROOT_USER}'
      POSTGRES_PASSWORD: '${POSTGRESQL_ROOT_USER_PASSWORD}'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data:rw'
    ports:
      - '${POSTGRESQL_PORT}:5432'
    restart: unless-stopped
    labels:
      com.axinom.service: 'Navy'
 
  pgadmin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: pgAdmin
      PGADMIN_DEFAULT_PASSWORD: pgAdmin
    volumes:
      - 'pgadmin_data:/var/lib/pgadmin:rw'
    ports:
      - '${PGADMIN_PORT}:80'
    restart: unless-stopped
    labels:
      com.axinom.service: 'Navy'
 
volumes:
  postgres_data:
  pgadmin_data:
