/* Autogenerated section below, manual changes done here will be lost */
// TODO: Implement autogeneration logic :)

export enum Endpoints {
  // Application
  application = 'application',
  applications = 'applications',
  createApplication = 'createApplication',
  deleteApplication = 'deleteApplication',
  updateApplication = 'updateApplication',

  // IdpConfiguration
  idpConfiguration = 'idpConfiguration',
  idpConfigurations = 'idpConfigurations',
  createIdpConfiguration = 'createIdpConfiguration',
  updateIdpConfiguration = 'updateIdpConfiguration',
  deleteIdpConfiguration = 'deleteIdpConfiguration',

  // IdpScopes
  idpScope = 'idpScope',
  idpScopes = 'idpScopes',

  // Identity Service - Tenant Aministrators
  authenticateTenantAdmin = 'authenticateTenantAdmin',
  changeTenantAdminPassword = 'changeTenantAdminPassword',
}
