/* Autogenerated section below, manual changes done here will be lost */
// TODO: Implement autogeneration logic :)

export enum Endpoints {
  // Tenant
  tenant = 'tenant',
  tenants = 'tenants',
  createTenant = 'createTenant',
  deleteTenant = 'deleteTenant',
  updateTenant = 'updateTenant',

  // TenantAdmin
  tenantAdmin = 'tenantAdmin',
  tenantAdmins = 'tenantAdmins',
  createTenantAdmin = 'createTenantAdmin',
  deleteTenantAdmin = 'deleteTenantAdmin',
  updateTenantAdmin = 'updateTenantAdmin',
  generateTenantAdminPassword = 'generateTenantAdminPassword',

  // Identity Service Super Users
  authenticateSuperUser = 'authenticateSuperUser',
}
